name: i++;
description: Blogging about devs
meta_description: "iMaisMais, Blogging about devs"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: "https://imaismais.top"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Your Name"

# Disqus config
disqus-shortname: ""
